-- ═══════════════════════════════════════════════════════════════════
-- Cadência · dados de demonstração (semente 7 do motor de domínio)
-- 112 projetos, 20 pessoas, 4 times, 6 etapas e 13 itens de playbook.
-- Gerado por scripts/gerar-seed.ts. Para uma base limpa em produção,
-- basta não aplicar esta migração ou remover os dados depois.
-- ═══════════════════════════════════════════════════════════════════

-- ─────────────────────── cargos e premissas ───────────────────────
insert into cargos (nome, ordem) values
    ('Analista', 0),
    ('Analista Sênior', 1),
    ('Especialista', 2),
    ('Arquiteto de Dados', 3),
    ('Líder Técnico', 4),
    ('Gerente de Projeto', 5);

insert into premissas_cargo (
  cargo_id, jornada, fator_ausencia, tempo_institucional, produtivo_min, tolerancia,
  max_reunioes_dia, max_horas_dia, max_horas_semana, max_horas_mes,
  duracao_max_min, bloco_foco_min_min, janela_protegida_min
)
select c.id, v.jornada, v.ausencia, v.institucional, v.produtivo, v.tolerancia,
       v.reunioes_dia, v.horas_dia, v.horas_semana, v.horas_mes,
       v.duracao_max, v.bloco_foco, v.janela
from (values
    ('Analista', 40, 10, 3, 82, 4, 4, 3, 8, 30, 120, 120, 120),
    ('Analista Sênior', 40, 10, 4, 78, 5, 5, 3.5, 9, 34, 120, 120, 120),
    ('Especialista', 40, 12, 4, 75, 6, 5, 4, 10, 38, 120, 120, 120),
    ('Arquiteto de Dados', 40, 10, 3, 85, 3, 3, 2.5, 6, 22, 60, 180, 180),
    ('Líder Técnico', 40, 12, 6, 65, 8, 6, 5, 13, 48, 120, 120, 60),
    ('Gerente de Projeto', 40, 12, 6, 58, 10, 8, 6, 16, 60, 90, 60, 0)
) as v(cargo, jornada, ausencia, institucional, produtivo, tolerancia, reunioes_dia,
       horas_dia, horas_semana, horas_mes, duracao_max, bloco_foco, janela)
join cargos c on c.nome = v.cargo;

-- ─────────────────────── premissas gerais (§2.2) ───────────────────────
-- Horários em slots de 30 minutos a partir das 08:00, como no motor.
insert into premissas_gerais (chave, valor) values
    ('inicio_jornada', '0'::jsonb),
    ('fim_jornada', '20'::jsonb),
    ('almoco_inicio', '8'::jsonb),
    ('almoco_duracao', '2'::jsonb),
    ('intervalo_entre_reunioes', '1'::jsonb),
    ('horarios_preferidos', '[4,5,6,7,10,11,12,13,14,15]'::jsonb),
    ('peso_preferencia', '1.5'::jsonb),
    ('dia_protegido', '"nenhum"'::jsonb),
    ('quorum_minimo_pct', '100'::jsonb),
    ('antecedencia_horas', '48'::jsonb),
    ('estabilidade_max_pct', '20'::jsonb);

-- ─────────────────────── etapas e prioridades ───────────────────────
insert into etapas (chave, rotulo, ordem, urgencia, prazo_dias, hue) values
    ('kickoff', 'Kickoff', 0, 5, 7, 300),
    ('discovery', 'Discovery', 1, 4, 10, 245),
    ('construcao', 'Construção', 2, 2, 15, 145),
    ('homologacao', 'Homologação', 3, 4, 10, 35),
    ('golive', 'Go-live', 4, 5, 5, 170),
    ('sustentacao', 'Sustentação', 5, 1, 30, 95);

insert into prioridades_cliente (nivel, peso) values
    ('alta', 3),
    ('media', 2),
    ('baixa', 1);

-- ─────────────────────── playbook (§3.1) ───────────────────────
insert into tipos_cerimonia (nome, hue) values
    ('Kickoff Executivo', 300),
    ('Levantamento de Requisitos', 250),
    ('Reunião de Trabalho', 145),
    ('Status Report', 85),
    ('Validação de Dados', 225),
    ('Validação de Produto', 210),
    ('Sessão de Homologação', 35),
    ('Acompanhamento Pós Go-live', 170),
    ('Treinamento de Usuários', 60),
    ('Check-in de Sustentação', 110);

insert into playbook_itens (etapa_id, tipo_cerimonia_id, duracao_min, cadencia_semanas, prioridade, obrigatoria, ordem)
select e.id, tc.id, v.duracao, v.cadencia, v.prioridade, v.obrigatoria, v.ordem
from (values
    ('kickoff', 'Kickoff Executivo', 60, 2, 1, true, 0),
    ('kickoff', 'Levantamento de Requisitos', 90, 1, 2, true, 1),
    ('discovery', 'Reunião de Trabalho', 90, 1, 2, true, 0),
    ('discovery', 'Status Report', 45, 3, 3, true, 1),
    ('discovery', 'Validação de Dados', 60, 4, 5, false, 2),
    ('construcao', 'Reunião de Trabalho', 60, 4, 2, true, 0),
    ('construcao', 'Status Report', 30, 6, 3, true, 1),
    ('construcao', 'Validação de Produto', 60, 8, 5, false, 2),
    ('homologacao', 'Sessão de Homologação', 90, 1, 1, true, 0),
    ('homologacao', 'Status Report', 45, 2, 3, true, 1),
    ('golive', 'Acompanhamento Pós Go-live', 30, 2, 2, true, 0),
    ('golive', 'Treinamento de Usuários', 120, 8, 4, false, 1),
    ('sustentacao', 'Check-in de Sustentação', 30, 8, 4, true, 0)
) as v(etapa, tipo, duracao, cadencia, prioridade, obrigatoria, ordem)
join etapas e on e.chave = v.etapa
join tipos_cerimonia tc on tc.nome = v.tipo;

insert into playbook_item_cargos (playbook_item_id, cargo_id)
select i.id, c.id
from (values
    ('kickoff', 'Kickoff Executivo', 'Gerente de Projeto'),
    ('kickoff', 'Kickoff Executivo', 'Analista Sênior'),
    ('kickoff', 'Kickoff Executivo', 'Líder Técnico'),
    ('kickoff', 'Levantamento de Requisitos', 'Especialista'),
    ('kickoff', 'Levantamento de Requisitos', 'Analista Sênior'),
    ('discovery', 'Reunião de Trabalho', 'Analista'),
    ('discovery', 'Reunião de Trabalho', 'Especialista'),
    ('discovery', 'Status Report', 'Gerente de Projeto'),
    ('discovery', 'Status Report', 'Analista Sênior'),
    ('discovery', 'Validação de Dados', 'Arquiteto de Dados'),
    ('discovery', 'Validação de Dados', 'Analista Sênior'),
    ('construcao', 'Reunião de Trabalho', 'Analista'),
    ('construcao', 'Reunião de Trabalho', 'Especialista'),
    ('construcao', 'Status Report', 'Líder Técnico'),
    ('construcao', 'Validação de Produto', 'Analista Sênior'),
    ('construcao', 'Validação de Produto', 'Especialista'),
    ('homologacao', 'Sessão de Homologação', 'Especialista'),
    ('homologacao', 'Sessão de Homologação', 'Analista Sênior'),
    ('homologacao', 'Status Report', 'Gerente de Projeto'),
    ('homologacao', 'Status Report', 'Líder Técnico'),
    ('golive', 'Acompanhamento Pós Go-live', 'Analista'),
    ('golive', 'Treinamento de Usuários', 'Especialista'),
    ('golive', 'Treinamento de Usuários', 'Analista'),
    ('sustentacao', 'Check-in de Sustentação', 'Analista')
) as v(etapa, tipo, cargo)
join etapas e on e.chave = v.etapa
join tipos_cerimonia tc on tc.nome = v.tipo
join playbook_itens i on i.etapa_id = e.id and i.tipo_cerimonia_id = tc.id
join cargos c on c.nome = v.cargo;

-- ─────────────────────── pessoas e times ───────────────────────
insert into pessoas (nome, iniciais, cargo_id, email)
select v.nome, v.iniciais, c.id, v.email
from (values
    ('Ana Ribeiro', 'AR', 'Analista', 'ana.ribeiro@leverpro.com.br'),
    ('Bruno Tavares', 'BT', 'Analista', 'bruno.tavares@leverpro.com.br'),
    ('Camila Duarte', 'CD', 'Analista', 'camila.duarte@leverpro.com.br'),
    ('Diego Falcão', 'DF', 'Analista', 'diego.falcao@leverpro.com.br'),
    ('Eduarda Nunes', 'EN', 'Analista', 'eduarda.nunes@leverpro.com.br'),
    ('Felipe Marques', 'FM', 'Especialista', 'felipe.marques@leverpro.com.br'),
    ('Gabriela Rocha', 'GR', 'Especialista', 'gabriela.rocha@leverpro.com.br'),
    ('Henrique Sales', 'HS', 'Especialista', 'henrique.sales@leverpro.com.br'),
    ('Isabela Prado', 'IP', 'Especialista', 'isabela.prado@leverpro.com.br'),
    ('João Vasques', 'JV', 'Especialista', 'joao.vasques@leverpro.com.br'),
    ('Karina Lopes', 'KL', 'Especialista', 'karina.lopes@leverpro.com.br'),
    ('Leandro Bastos', 'LB', 'Especialista', 'leandro.bastos@leverpro.com.br'),
    ('Mariana Cordeiro', 'MC', 'Analista Sênior', 'mariana.cordeiro@leverpro.com.br'),
    ('Nelson Braga', 'NB', 'Analista Sênior', 'nelson.braga@leverpro.com.br'),
    ('Otávio Lima', 'OL', 'Analista Sênior', 'otavio.lima@leverpro.com.br'),
    ('Paula Monteiro', 'PM', 'Analista Sênior', 'paula.monteiro@leverpro.com.br'),
    ('Rafael Antunes', 'RA', 'Arquiteto de Dados', 'rafael.antunes@leverpro.com.br'),
    ('Sofia Mendes', 'SM', 'Líder Técnico', 'sofia.mendes@leverpro.com.br'),
    ('Thiago Rezende', 'TR', 'Gerente de Projeto', 'thiago.rezende@leverpro.com.br'),
    ('Vanessa Klein', 'VK', 'Gerente de Projeto', 'vanessa.klein@leverpro.com.br')
) as v(nome, iniciais, cargo, email)
join cargos c on c.nome = v.cargo;

insert into times (nome) values
    ('Squad Alfa'),
    ('Squad Bravo'),
    ('Squad Charlie'),
    ('Squad Delta');

insert into time_membros (time_id, pessoa_id)
select tm.id, p.id
from (values
    ('Squad Alfa', 'Ana Ribeiro'),
    ('Squad Alfa', 'Eduarda Nunes'),
    ('Squad Alfa', 'Felipe Marques'),
    ('Squad Alfa', 'João Vasques'),
    ('Squad Alfa', 'Mariana Cordeiro'),
    ('Squad Alfa', 'Rafael Antunes'),
    ('Squad Alfa', 'Sofia Mendes'),
    ('Squad Alfa', 'Thiago Rezende'),
    ('Squad Alfa', 'Vanessa Klein'),
    ('Squad Bravo', 'Bruno Tavares'),
    ('Squad Bravo', 'Gabriela Rocha'),
    ('Squad Bravo', 'Karina Lopes'),
    ('Squad Bravo', 'Nelson Braga'),
    ('Squad Bravo', 'Rafael Antunes'),
    ('Squad Bravo', 'Sofia Mendes'),
    ('Squad Bravo', 'Thiago Rezende'),
    ('Squad Bravo', 'Vanessa Klein'),
    ('Squad Charlie', 'Camila Duarte'),
    ('Squad Charlie', 'Henrique Sales'),
    ('Squad Charlie', 'Leandro Bastos'),
    ('Squad Charlie', 'Otávio Lima'),
    ('Squad Charlie', 'Rafael Antunes'),
    ('Squad Charlie', 'Sofia Mendes'),
    ('Squad Charlie', 'Thiago Rezende'),
    ('Squad Charlie', 'Vanessa Klein'),
    ('Squad Delta', 'Diego Falcão'),
    ('Squad Delta', 'Isabela Prado'),
    ('Squad Delta', 'Paula Monteiro'),
    ('Squad Delta', 'Rafael Antunes'),
    ('Squad Delta', 'Sofia Mendes'),
    ('Squad Delta', 'Thiago Rezende'),
    ('Squad Delta', 'Vanessa Klein')
) as v(time, pessoa)
join times tm on tm.nome = v.time
join pessoas p on p.nome = v.pessoa;

-- ─────────────────────── clientes e projetos ───────────────────────
insert into clientes (nome, prioridade) values
    ('Grupo Vértice', 'media'),
    ('Agro Everest', 'baixa'),
    ('Indústrias Ferrolar', 'baixa'),
    ('Indústrias Urano', 'baixa'),
    ('Indústrias Cristalina', 'alta'),
    ('Log Horizonte', 'media'),
    ('Holding Serra Azul', 'baixa'),
    ('Grupo Rubi', 'baixa'),
    ('Agro Bandeirante', 'media'),
    ('Grupo Marfim', 'baixa'),
    ('Log Jacarandá', 'baixa'),
    ('Grupo Diamantina', 'alta'),
    ('Holding Estrela', 'baixa'),
    ('Indústrias Ourivés', 'media'),
    ('Agro Estrela', 'baixa'),
    ('Log Zênite', 'media'),
    ('Rede Lumina', 'alta'),
    ('Med Vértice', 'media'),
    ('Log Solaris', 'baixa'),
    ('Log Montana', 'baixa'),
    ('Med Everest', 'media'),
    ('Rede Guaraí', 'media'),
    ('Rede Jacarandá', 'baixa'),
    ('Rede Pampulha', 'media'),
    ('Holding Everest', 'baixa'),
    ('Cia Estrela', 'media'),
    ('Agro Pampulha', 'media'),
    ('Rede Nortis', 'baixa'),
    ('Indústrias Itaúna', 'media'),
    ('Agro Verdaz', 'baixa'),
    ('Log Ipê', 'baixa'),
    ('Agro Vértice', 'baixa'),
    ('Log Ferrolar', 'baixa'),
    ('Holding Xisto', 'media'),
    ('Holding Marfim', 'media'),
    ('Cia Delta Sul', 'baixa'),
    ('Rede Ourivés', 'alta'),
    ('Holding Horizonte', 'baixa'),
    ('Agro Solaris', 'media'),
    ('Indústrias Rubi', 'baixa'),
    ('Rede Xisto', 'media'),
    ('Rede Diamantina', 'media'),
    ('Log Kaporã', 'media'),
    ('Med Andorra', 'alta'),
    ('Grupo Lumina', 'media'),
    ('Agro Ferrolar', 'baixa'),
    ('Log Tramontana', 'baixa'),
    ('Holding Andorra', 'baixa'),
    ('Med Ipê', 'media'),
    ('Med Marfim', 'media'),
    ('Log Nortis', 'media'),
    ('Log Andorra', 'alta'),
    ('Agro Zênite', 'media'),
    ('Rede Horizonte', 'alta'),
    ('Rede Urano', 'baixa'),
    ('Log Verdaz', 'baixa'),
    ('Log Vértice', 'media'),
    ('Holding Aurora', 'media'),
    ('Agro Tramontana', 'baixa'),
    ('Med Cristalina', 'baixa'),
    ('Rede Rubi', 'baixa'),
    ('Log Guaraí', 'media'),
    ('Indústrias Ipê', 'baixa'),
    ('Grupo Guaraí', 'media'),
    ('Rede Solaris', 'baixa'),
    ('Rede Vértice', 'baixa'),
    ('Rede Marfim', 'baixa'),
    ('Holding Lumina', 'baixa'),
    ('Log Diamantina', 'media'),
    ('Med Xisto', 'baixa'),
    ('Rede Delta Sul', 'media'),
    ('Indústrias Diamantina', 'baixa'),
    ('Cia Marfim', 'alta'),
    ('Med Kaporã', 'media'),
    ('Log Lumina', 'baixa'),
    ('Cia Serra Azul', 'media'),
    ('Log Bandeirante', 'media'),
    ('Grupo Xisto', 'alta'),
    ('Indústrias Horizonte', 'alta'),
    ('Holding Rubi', 'media'),
    ('Holding Urano', 'baixa'),
    ('Log Everest', 'media'),
    ('Med Nortis', 'media'),
    ('Indústrias Tramontana', 'baixa'),
    ('Grupo Câmbio', 'baixa'),
    ('Cia Ourivés', 'baixa'),
    ('Cia Horizonte', 'alta'),
    ('Indústrias Estrela', 'baixa'),
    ('Agro Cristalina', 'media'),
    ('Med Urano', 'media'),
    ('Holding Bandeirante', 'baixa'),
    ('Indústrias Aurora', 'baixa'),
    ('Indústrias Nortis', 'alta'),
    ('Agro Ipê', 'media'),
    ('Cia Nortis', 'baixa');

insert into projetos (cliente_id, nome, etapa_id, time_id, mes, health, prioridade)
select cl.id, v.nome, e.id, tm.id, v.mes, v.health::health_projeto, v.prioridade::prioridade_cliente
from (values
    ('Grupo Vértice', 'Grupo Vértice A', 'kickoff', 'Squad Charlie', 8, 'amarelo', 'media'),
    ('Agro Everest', 'Agro Everest B', 'kickoff', 'Squad Delta', 5, 'verde', 'baixa'),
    ('Indústrias Ferrolar', 'Indústrias Ferrolar C', 'kickoff', 'Squad Delta', 5, 'amarelo', 'baixa'),
    ('Indústrias Urano', 'Indústrias Urano D', 'kickoff', 'Squad Charlie', 14, 'verde', 'baixa'),
    ('Indústrias Cristalina', 'Indústrias Cristalina E', 'discovery', 'Squad Bravo', 2, 'amarelo', 'alta'),
    ('Log Horizonte', 'Log Horizonte F', 'discovery', 'Squad Bravo', 5, 'verde', 'media'),
    ('Holding Serra Azul', 'Holding Serra Azul G', 'discovery', 'Squad Bravo', 5, 'verde', 'baixa'),
    ('Grupo Rubi', 'Grupo Rubi H', 'discovery', 'Squad Charlie', 8, 'amarelo', 'baixa'),
    ('Agro Bandeirante', 'Agro Bandeirante I', 'discovery', 'Squad Alfa', 12, 'vermelho', 'media'),
    ('Grupo Marfim', 'Grupo Marfim J', 'discovery', 'Squad Delta', 8, 'verde', 'baixa'),
    ('Log Jacarandá', 'Log Jacarandá K', 'discovery', 'Squad Bravo', 1, 'verde', 'baixa'),
    ('Grupo Diamantina', 'Grupo Diamantina L', 'discovery', 'Squad Alfa', 14, 'amarelo', 'alta'),
    ('Holding Estrela', 'Holding Estrela M', 'discovery', 'Squad Alfa', 14, 'verde', 'baixa'),
    ('Indústrias Ourivés', 'Indústrias Ourivés N', 'discovery', 'Squad Alfa', 11, 'verde', 'media'),
    ('Agro Estrela', 'Agro Estrela O', 'construcao', 'Squad Alfa', 9, 'verde', 'baixa'),
    ('Log Zênite', 'Log Zênite P', 'construcao', 'Squad Charlie', 4, 'verde', 'media'),
    ('Rede Lumina', 'Rede Lumina Q', 'construcao', 'Squad Delta', 13, 'verde', 'alta'),
    ('Med Vértice', 'Med Vértice R', 'construcao', 'Squad Alfa', 6, 'verde', 'media'),
    ('Log Solaris', 'Log Solaris S', 'construcao', 'Squad Delta', 8, 'amarelo', 'baixa'),
    ('Log Montana', 'Log Montana T', 'construcao', 'Squad Bravo', 5, 'verde', 'baixa'),
    ('Med Everest', 'Med Everest U', 'construcao', 'Squad Charlie', 8, 'verde', 'media'),
    ('Rede Guaraí', 'Rede Guaraí V', 'construcao', 'Squad Bravo', 12, 'verde', 'media'),
    ('Rede Jacarandá', 'Rede Jacarandá W', 'construcao', 'Squad Alfa', 10, 'verde', 'baixa'),
    ('Rede Pampulha', 'Rede Pampulha X', 'construcao', 'Squad Delta', 14, 'amarelo', 'media'),
    ('Holding Everest', 'Holding Everest Y', 'construcao', 'Squad Alfa', 14, 'verde', 'baixa'),
    ('Cia Estrela', 'Cia Estrela Z', 'construcao', 'Squad Bravo', 9, 'verde', 'media'),
    ('Agro Pampulha', 'Agro Pampulha A', 'construcao', 'Squad Alfa', 11, 'verde', 'media'),
    ('Rede Nortis', 'Rede Nortis B', 'construcao', 'Squad Alfa', 5, 'verde', 'baixa'),
    ('Indústrias Itaúna', 'Indústrias Itaúna C', 'construcao', 'Squad Bravo', 13, 'vermelho', 'media'),
    ('Agro Verdaz', 'Agro Verdaz D', 'construcao', 'Squad Bravo', 3, 'verde', 'baixa'),
    ('Log Ipê', 'Log Ipê E', 'construcao', 'Squad Charlie', 12, 'verde', 'baixa'),
    ('Agro Vértice', 'Agro Vértice F', 'construcao', 'Squad Alfa', 12, 'verde', 'baixa'),
    ('Agro Everest', 'Agro Everest G', 'construcao', 'Squad Alfa', 3, 'verde', 'alta'),
    ('Log Ferrolar', 'Log Ferrolar H', 'construcao', 'Squad Bravo', 13, 'verde', 'baixa'),
    ('Holding Xisto', 'Holding Xisto I', 'construcao', 'Squad Bravo', 10, 'verde', 'media'),
    ('Holding Marfim', 'Holding Marfim J', 'construcao', 'Squad Bravo', 11, 'verde', 'media'),
    ('Cia Delta Sul', 'Cia Delta Sul K', 'construcao', 'Squad Alfa', 13, 'verde', 'baixa'),
    ('Rede Ourivés', 'Rede Ourivés L', 'construcao', 'Squad Delta', 11, 'verde', 'alta'),
    ('Log Montana', 'Log Montana M', 'homologacao', 'Squad Bravo', 3, 'verde', 'media'),
    ('Holding Horizonte', 'Holding Horizonte N', 'homologacao', 'Squad Bravo', 9, 'vermelho', 'baixa'),
    ('Agro Solaris', 'Agro Solaris O', 'homologacao', 'Squad Charlie', 7, 'verde', 'media'),
    ('Indústrias Rubi', 'Indústrias Rubi P', 'homologacao', 'Squad Charlie', 7, 'verde', 'baixa'),
    ('Rede Xisto', 'Rede Xisto Q', 'homologacao', 'Squad Delta', 2, 'verde', 'media'),
    ('Rede Diamantina', 'Rede Diamantina R', 'homologacao', 'Squad Delta', 1, 'verde', 'media'),
    ('Log Kaporã', 'Log Kaporã S', 'homologacao', 'Squad Alfa', 8, 'verde', 'media'),
    ('Med Andorra', 'Med Andorra T', 'homologacao', 'Squad Bravo', 4, 'verde', 'alta'),
    ('Grupo Lumina', 'Grupo Lumina U', 'golive', 'Squad Delta', 8, 'verde', 'media'),
    ('Agro Ferrolar', 'Agro Ferrolar V', 'golive', 'Squad Charlie', 10, 'verde', 'baixa'),
    ('Log Tramontana', 'Log Tramontana W', 'golive', 'Squad Bravo', 9, 'verde', 'baixa'),
    ('Indústrias Rubi', 'Indústrias Rubi X', 'golive', 'Squad Charlie', 3, 'vermelho', 'baixa'),
    ('Holding Estrela', 'Holding Estrela Y', 'golive', 'Squad Bravo', 12, 'verde', 'baixa'),
    ('Holding Andorra', 'Holding Andorra Z', 'golive', 'Squad Delta', 5, 'verde', 'baixa'),
    ('Med Ipê', 'Med Ipê A', 'sustentacao', 'Squad Bravo', 1, 'verde', 'media'),
    ('Med Marfim', 'Med Marfim B', 'sustentacao', 'Squad Bravo', 10, 'amarelo', 'media'),
    ('Log Nortis', 'Log Nortis C', 'sustentacao', 'Squad Charlie', 4, 'amarelo', 'media'),
    ('Log Andorra', 'Log Andorra D', 'sustentacao', 'Squad Bravo', 9, 'verde', 'alta'),
    ('Agro Zênite', 'Agro Zênite E', 'sustentacao', 'Squad Alfa', 3, 'verde', 'media'),
    ('Rede Horizonte', 'Rede Horizonte F', 'sustentacao', 'Squad Charlie', 1, 'verde', 'alta'),
    ('Rede Urano', 'Rede Urano G', 'sustentacao', 'Squad Bravo', 13, 'amarelo', 'baixa'),
    ('Log Verdaz', 'Log Verdaz H', 'sustentacao', 'Squad Delta', 5, 'amarelo', 'baixa'),
    ('Log Vértice', 'Log Vértice I', 'sustentacao', 'Squad Charlie', 13, 'verde', 'media'),
    ('Holding Aurora', 'Holding Aurora J', 'sustentacao', 'Squad Bravo', 3, 'verde', 'media'),
    ('Agro Tramontana', 'Agro Tramontana K', 'sustentacao', 'Squad Delta', 8, 'vermelho', 'baixa'),
    ('Med Cristalina', 'Med Cristalina L', 'sustentacao', 'Squad Bravo', 4, 'verde', 'baixa'),
    ('Rede Diamantina', 'Rede Diamantina M', 'sustentacao', 'Squad Charlie', 9, 'amarelo', 'baixa'),
    ('Log Montana', 'Log Montana N', 'sustentacao', 'Squad Alfa', 8, 'vermelho', 'alta'),
    ('Rede Diamantina', 'Rede Diamantina O', 'sustentacao', 'Squad Bravo', 8, 'amarelo', 'baixa'),
    ('Rede Rubi', 'Rede Rubi P', 'sustentacao', 'Squad Charlie', 2, 'verde', 'baixa'),
    ('Log Guaraí', 'Log Guaraí Q', 'sustentacao', 'Squad Delta', 7, 'verde', 'media'),
    ('Indústrias Ipê', 'Indústrias Ipê R', 'sustentacao', 'Squad Delta', 14, 'amarelo', 'baixa'),
    ('Agro Vértice', 'Agro Vértice S', 'sustentacao', 'Squad Delta', 3, 'verde', 'media'),
    ('Grupo Lumina', 'Grupo Lumina T', 'sustentacao', 'Squad Charlie', 5, 'verde', 'baixa'),
    ('Grupo Guaraí', 'Grupo Guaraí U', 'sustentacao', 'Squad Charlie', 2, 'verde', 'media'),
    ('Rede Solaris', 'Rede Solaris V', 'sustentacao', 'Squad Charlie', 12, 'amarelo', 'baixa'),
    ('Rede Vértice', 'Rede Vértice W', 'sustentacao', 'Squad Delta', 10, 'verde', 'baixa'),
    ('Rede Marfim', 'Rede Marfim X', 'sustentacao', 'Squad Charlie', 12, 'amarelo', 'baixa'),
    ('Holding Lumina', 'Holding Lumina Y', 'sustentacao', 'Squad Charlie', 13, 'verde', 'baixa'),
    ('Log Diamantina', 'Log Diamantina Z', 'sustentacao', 'Squad Delta', 3, 'amarelo', 'media'),
    ('Grupo Guaraí', 'Grupo Guaraí A', 'sustentacao', 'Squad Delta', 2, 'verde', 'media'),
    ('Med Xisto', 'Med Xisto B', 'sustentacao', 'Squad Delta', 12, 'verde', 'baixa'),
    ('Holding Serra Azul', 'Holding Serra Azul C', 'sustentacao', 'Squad Charlie', 4, 'verde', 'alta'),
    ('Rede Delta Sul', 'Rede Delta Sul D', 'sustentacao', 'Squad Delta', 9, 'amarelo', 'media'),
    ('Indústrias Diamantina', 'Indústrias Diamantina E', 'sustentacao', 'Squad Delta', 7, 'amarelo', 'baixa'),
    ('Cia Marfim', 'Cia Marfim F', 'sustentacao', 'Squad Alfa', 8, 'verde', 'alta'),
    ('Med Kaporã', 'Med Kaporã G', 'sustentacao', 'Squad Delta', 14, 'vermelho', 'media'),
    ('Log Lumina', 'Log Lumina H', 'sustentacao', 'Squad Delta', 10, 'verde', 'baixa'),
    ('Cia Serra Azul', 'Cia Serra Azul I', 'sustentacao', 'Squad Alfa', 9, 'verde', 'media'),
    ('Log Bandeirante', 'Log Bandeirante J', 'sustentacao', 'Squad Charlie', 6, 'verde', 'media'),
    ('Grupo Xisto', 'Grupo Xisto K', 'sustentacao', 'Squad Charlie', 1, 'verde', 'alta'),
    ('Indústrias Horizonte', 'Indústrias Horizonte L', 'sustentacao', 'Squad Charlie', 4, 'verde', 'alta'),
    ('Holding Rubi', 'Holding Rubi M', 'sustentacao', 'Squad Bravo', 13, 'verde', 'media'),
    ('Holding Urano', 'Holding Urano N', 'sustentacao', 'Squad Alfa', 11, 'verde', 'baixa'),
    ('Indústrias Rubi', 'Indústrias Rubi O', 'sustentacao', 'Squad Alfa', 13, 'vermelho', 'baixa'),
    ('Log Everest', 'Log Everest P', 'sustentacao', 'Squad Alfa', 14, 'verde', 'media'),
    ('Med Nortis', 'Med Nortis Q', 'sustentacao', 'Squad Alfa', 5, 'amarelo', 'media'),
    ('Indústrias Tramontana', 'Indústrias Tramontana R', 'sustentacao', 'Squad Alfa', 6, 'verde', 'baixa'),
    ('Indústrias Tramontana', 'Indústrias Tramontana S', 'sustentacao', 'Squad Charlie', 7, 'verde', 'baixa'),
    ('Grupo Câmbio', 'Grupo Câmbio T', 'sustentacao', 'Squad Charlie', 14, 'verde', 'baixa'),
    ('Cia Ourivés', 'Cia Ourivés U', 'sustentacao', 'Squad Alfa', 14, 'verde', 'baixa'),
    ('Rede Ourivés', 'Rede Ourivés V', 'sustentacao', 'Squad Alfa', 2, 'verde', 'media'),
    ('Cia Horizonte', 'Cia Horizonte W', 'sustentacao', 'Squad Bravo', 14, 'verde', 'alta'),
    ('Indústrias Estrela', 'Indústrias Estrela X', 'sustentacao', 'Squad Alfa', 1, 'verde', 'baixa'),
    ('Cia Estrela', 'Cia Estrela Y', 'sustentacao', 'Squad Bravo', 7, 'vermelho', 'baixa'),
    ('Indústrias Tramontana', 'Indústrias Tramontana Z', 'sustentacao', 'Squad Alfa', 4, 'verde', 'alta'),
    ('Agro Cristalina', 'Agro Cristalina A', 'sustentacao', 'Squad Charlie', 5, 'verde', 'media'),
    ('Indústrias Cristalina', 'Indústrias Cristalina B', 'sustentacao', 'Squad Alfa', 8, 'verde', 'media'),
    ('Med Urano', 'Med Urano C', 'sustentacao', 'Squad Delta', 3, 'amarelo', 'media'),
    ('Holding Bandeirante', 'Holding Bandeirante D', 'sustentacao', 'Squad Bravo', 7, 'verde', 'baixa'),
    ('Indústrias Aurora', 'Indústrias Aurora E', 'sustentacao', 'Squad Delta', 2, 'verde', 'baixa'),
    ('Indústrias Nortis', 'Indústrias Nortis F', 'sustentacao', 'Squad Delta', 6, 'verde', 'alta'),
    ('Agro Ipê', 'Agro Ipê G', 'sustentacao', 'Squad Charlie', 8, 'verde', 'media'),
    ('Cia Nortis', 'Cia Nortis H', 'sustentacao', 'Squad Delta', 13, 'amarelo', 'baixa')
) as v(cliente, nome, etapa, time, mes, health, prioridade)
join clientes cl on cl.nome = v.cliente
join etapas e on e.chave = v.etapa
join times tm on tm.nome = v.time;

insert into produtos (projeto_id, tipo)
select p.id, v.tipo::tipo_produto
from (values
    ('Grupo Vértice A', 'relatorio', 4),
    ('Grupo Vértice A', 'dashboard', 3),
    ('Agro Everest B', 'relatorio', 5),
    ('Agro Everest B', 'dashboard', 1),
    ('Agro Everest B', 'integracao', 1),
    ('Indústrias Ferrolar C', 'relatorio', 3),
    ('Indústrias Ferrolar C', 'dashboard', 1),
    ('Indústrias Urano D', 'relatorio', 5),
    ('Indústrias Urano D', 'dashboard', 4),
    ('Indústrias Urano D', 'integracao', 2),
    ('Indústrias Cristalina E', 'relatorio', 4),
    ('Indústrias Cristalina E', 'dashboard', 3),
    ('Log Horizonte F', 'relatorio', 7),
    ('Log Horizonte F', 'dashboard', 4),
    ('Log Horizonte F', 'integracao', 2),
    ('Holding Serra Azul G', 'relatorio', 3),
    ('Holding Serra Azul G', 'dashboard', 1),
    ('Holding Serra Azul G', 'integracao', 1),
    ('Grupo Rubi H', 'relatorio', 5),
    ('Grupo Rubi H', 'dashboard', 5),
    ('Agro Bandeirante I', 'relatorio', 7),
    ('Agro Bandeirante I', 'dashboard', 5),
    ('Agro Bandeirante I', 'integracao', 1),
    ('Grupo Marfim J', 'relatorio', 5),
    ('Grupo Marfim J', 'dashboard', 4),
    ('Grupo Marfim J', 'integracao', 2),
    ('Log Jacarandá K', 'relatorio', 5),
    ('Log Jacarandá K', 'dashboard', 2),
    ('Grupo Diamantina L', 'relatorio', 5),
    ('Grupo Diamantina L', 'dashboard', 3),
    ('Grupo Diamantina L', 'integracao', 2),
    ('Holding Estrela M', 'relatorio', 5),
    ('Holding Estrela M', 'dashboard', 5),
    ('Indústrias Ourivés N', 'relatorio', 3),
    ('Indústrias Ourivés N', 'dashboard', 5),
    ('Indústrias Ourivés N', 'integracao', 2),
    ('Agro Estrela O', 'relatorio', 7),
    ('Agro Estrela O', 'dashboard', 3),
    ('Log Zênite P', 'relatorio', 4),
    ('Log Zênite P', 'dashboard', 3),
    ('Rede Lumina Q', 'relatorio', 3),
    ('Rede Lumina Q', 'dashboard', 1),
    ('Med Vértice R', 'relatorio', 4),
    ('Med Vértice R', 'dashboard', 4),
    ('Med Vértice R', 'integracao', 1),
    ('Log Solaris S', 'relatorio', 4),
    ('Log Solaris S', 'dashboard', 3),
    ('Log Montana T', 'relatorio', 6),
    ('Log Montana T', 'dashboard', 4),
    ('Log Montana T', 'integracao', 1),
    ('Med Everest U', 'relatorio', 6),
    ('Med Everest U', 'dashboard', 3),
    ('Med Everest U', 'integracao', 2),
    ('Rede Guaraí V', 'relatorio', 7),
    ('Rede Guaraí V', 'dashboard', 3),
    ('Rede Guaraí V', 'integracao', 2),
    ('Rede Jacarandá W', 'relatorio', 5),
    ('Rede Jacarandá W', 'dashboard', 4),
    ('Rede Pampulha X', 'relatorio', 2),
    ('Rede Pampulha X', 'dashboard', 4),
    ('Rede Pampulha X', 'integracao', 2),
    ('Holding Everest Y', 'relatorio', 7),
    ('Holding Everest Y', 'dashboard', 4),
    ('Holding Everest Y', 'integracao', 2),
    ('Cia Estrela Z', 'relatorio', 4),
    ('Cia Estrela Z', 'dashboard', 4),
    ('Cia Estrela Z', 'integracao', 2),
    ('Agro Pampulha A', 'relatorio', 6),
    ('Agro Pampulha A', 'dashboard', 3),
    ('Rede Nortis B', 'relatorio', 7),
    ('Rede Nortis B', 'dashboard', 1),
    ('Indústrias Itaúna C', 'relatorio', 7),
    ('Indústrias Itaúna C', 'dashboard', 2),
    ('Indústrias Itaúna C', 'integracao', 1),
    ('Agro Verdaz D', 'relatorio', 7),
    ('Agro Verdaz D', 'dashboard', 5),
    ('Log Ipê E', 'relatorio', 3),
    ('Log Ipê E', 'dashboard', 3),
    ('Agro Vértice F', 'relatorio', 2),
    ('Agro Vértice F', 'dashboard', 1),
    ('Agro Vértice F', 'integracao', 1),
    ('Agro Everest G', 'relatorio', 4),
    ('Agro Everest G', 'dashboard', 3),
    ('Agro Everest G', 'integracao', 1),
    ('Log Ferrolar H', 'relatorio', 2),
    ('Log Ferrolar H', 'dashboard', 1),
    ('Log Ferrolar H', 'integracao', 2),
    ('Holding Xisto I', 'relatorio', 2),
    ('Holding Xisto I', 'dashboard', 1),
    ('Holding Xisto I', 'integracao', 2),
    ('Holding Marfim J', 'relatorio', 4),
    ('Holding Marfim J', 'dashboard', 4),
    ('Cia Delta Sul K', 'relatorio', 2),
    ('Cia Delta Sul K', 'dashboard', 1),
    ('Cia Delta Sul K', 'integracao', 2),
    ('Rede Ourivés L', 'relatorio', 5),
    ('Rede Ourivés L', 'dashboard', 1),
    ('Rede Ourivés L', 'integracao', 1),
    ('Log Montana M', 'relatorio', 2),
    ('Log Montana M', 'dashboard', 5),
    ('Holding Horizonte N', 'relatorio', 6),
    ('Holding Horizonte N', 'dashboard', 4),
    ('Holding Horizonte N', 'integracao', 2),
    ('Agro Solaris O', 'relatorio', 5),
    ('Agro Solaris O', 'dashboard', 2),
    ('Indústrias Rubi P', 'relatorio', 3),
    ('Indústrias Rubi P', 'dashboard', 4),
    ('Indústrias Rubi P', 'integracao', 1),
    ('Rede Xisto Q', 'relatorio', 5),
    ('Rede Xisto Q', 'dashboard', 4),
    ('Rede Xisto Q', 'integracao', 1),
    ('Rede Diamantina R', 'relatorio', 6),
    ('Rede Diamantina R', 'dashboard', 2),
    ('Rede Diamantina R', 'integracao', 2),
    ('Log Kaporã S', 'relatorio', 3),
    ('Log Kaporã S', 'dashboard', 5),
    ('Log Kaporã S', 'integracao', 2),
    ('Med Andorra T', 'relatorio', 2),
    ('Med Andorra T', 'dashboard', 4),
    ('Med Andorra T', 'integracao', 2),
    ('Grupo Lumina U', 'relatorio', 5),
    ('Grupo Lumina U', 'dashboard', 5),
    ('Agro Ferrolar V', 'relatorio', 2),
    ('Agro Ferrolar V', 'dashboard', 3),
    ('Agro Ferrolar V', 'integracao', 1),
    ('Log Tramontana W', 'relatorio', 5),
    ('Log Tramontana W', 'dashboard', 4),
    ('Log Tramontana W', 'integracao', 1),
    ('Indústrias Rubi X', 'relatorio', 7),
    ('Indústrias Rubi X', 'dashboard', 4),
    ('Indústrias Rubi X', 'integracao', 1),
    ('Holding Estrela Y', 'relatorio', 2),
    ('Holding Estrela Y', 'dashboard', 4),
    ('Holding Estrela Y', 'integracao', 1),
    ('Holding Andorra Z', 'relatorio', 5),
    ('Holding Andorra Z', 'dashboard', 2),
    ('Med Ipê A', 'relatorio', 6),
    ('Med Ipê A', 'dashboard', 1),
    ('Med Ipê A', 'integracao', 2),
    ('Med Marfim B', 'relatorio', 6),
    ('Med Marfim B', 'dashboard', 2),
    ('Med Marfim B', 'integracao', 1),
    ('Log Nortis C', 'relatorio', 3),
    ('Log Nortis C', 'dashboard', 1),
    ('Log Nortis C', 'integracao', 1),
    ('Log Andorra D', 'relatorio', 4),
    ('Log Andorra D', 'dashboard', 5),
    ('Log Andorra D', 'integracao', 2),
    ('Agro Zênite E', 'relatorio', 3),
    ('Agro Zênite E', 'dashboard', 3),
    ('Agro Zênite E', 'integracao', 1),
    ('Rede Horizonte F', 'relatorio', 5),
    ('Rede Horizonte F', 'dashboard', 3),
    ('Rede Urano G', 'relatorio', 7),
    ('Rede Urano G', 'dashboard', 5),
    ('Rede Urano G', 'integracao', 1),
    ('Log Verdaz H', 'relatorio', 3),
    ('Log Verdaz H', 'dashboard', 2),
    ('Log Verdaz H', 'integracao', 2),
    ('Log Vértice I', 'relatorio', 3),
    ('Log Vértice I', 'dashboard', 3),
    ('Log Vértice I', 'integracao', 1),
    ('Holding Aurora J', 'relatorio', 2),
    ('Holding Aurora J', 'dashboard', 1),
    ('Holding Aurora J', 'integracao', 1),
    ('Agro Tramontana K', 'relatorio', 5),
    ('Agro Tramontana K', 'dashboard', 5),
    ('Agro Tramontana K', 'integracao', 2),
    ('Med Cristalina L', 'relatorio', 6),
    ('Med Cristalina L', 'dashboard', 3),
    ('Med Cristalina L', 'integracao', 1),
    ('Rede Diamantina M', 'relatorio', 6),
    ('Rede Diamantina M', 'dashboard', 4),
    ('Rede Diamantina M', 'integracao', 2),
    ('Log Montana N', 'relatorio', 4),
    ('Log Montana N', 'dashboard', 4),
    ('Log Montana N', 'integracao', 2),
    ('Rede Diamantina O', 'relatorio', 3),
    ('Rede Diamantina O', 'dashboard', 3),
    ('Rede Diamantina O', 'integracao', 1),
    ('Rede Rubi P', 'relatorio', 2),
    ('Rede Rubi P', 'dashboard', 1),
    ('Rede Rubi P', 'integracao', 2),
    ('Log Guaraí Q', 'relatorio', 6),
    ('Log Guaraí Q', 'dashboard', 2),
    ('Indústrias Ipê R', 'relatorio', 5),
    ('Indústrias Ipê R', 'dashboard', 1),
    ('Indústrias Ipê R', 'integracao', 2),
    ('Agro Vértice S', 'relatorio', 3),
    ('Agro Vértice S', 'dashboard', 2),
    ('Agro Vértice S', 'integracao', 1),
    ('Grupo Lumina T', 'relatorio', 5),
    ('Grupo Lumina T', 'dashboard', 4),
    ('Grupo Lumina T', 'integracao', 1),
    ('Grupo Guaraí U', 'relatorio', 7),
    ('Grupo Guaraí U', 'dashboard', 1),
    ('Rede Solaris V', 'relatorio', 7),
    ('Rede Solaris V', 'dashboard', 3),
    ('Rede Solaris V', 'integracao', 2),
    ('Rede Vértice W', 'relatorio', 2),
    ('Rede Vértice W', 'dashboard', 2),
    ('Rede Vértice W', 'integracao', 2),
    ('Rede Marfim X', 'relatorio', 3),
    ('Rede Marfim X', 'dashboard', 1),
    ('Rede Marfim X', 'integracao', 2),
    ('Holding Lumina Y', 'relatorio', 2),
    ('Holding Lumina Y', 'dashboard', 1),
    ('Log Diamantina Z', 'relatorio', 4),
    ('Log Diamantina Z', 'dashboard', 1),
    ('Log Diamantina Z', 'integracao', 1),
    ('Grupo Guaraí A', 'relatorio', 5),
    ('Grupo Guaraí A', 'dashboard', 5),
    ('Grupo Guaraí A', 'integracao', 2),
    ('Med Xisto B', 'relatorio', 4),
    ('Med Xisto B', 'dashboard', 4),
    ('Med Xisto B', 'integracao', 2),
    ('Holding Serra Azul C', 'relatorio', 2),
    ('Holding Serra Azul C', 'dashboard', 4),
    ('Rede Delta Sul D', 'relatorio', 7),
    ('Rede Delta Sul D', 'dashboard', 2),
    ('Indústrias Diamantina E', 'relatorio', 7),
    ('Indústrias Diamantina E', 'dashboard', 4),
    ('Cia Marfim F', 'relatorio', 7),
    ('Cia Marfim F', 'dashboard', 1),
    ('Med Kaporã G', 'relatorio', 2),
    ('Med Kaporã G', 'dashboard', 1),
    ('Med Kaporã G', 'integracao', 1),
    ('Log Lumina H', 'relatorio', 6),
    ('Log Lumina H', 'dashboard', 2),
    ('Cia Serra Azul I', 'relatorio', 2),
    ('Cia Serra Azul I', 'dashboard', 2),
    ('Cia Serra Azul I', 'integracao', 2),
    ('Log Bandeirante J', 'relatorio', 7),
    ('Log Bandeirante J', 'dashboard', 3),
    ('Log Bandeirante J', 'integracao', 2),
    ('Grupo Xisto K', 'relatorio', 3),
    ('Grupo Xisto K', 'dashboard', 2),
    ('Grupo Xisto K', 'integracao', 2),
    ('Indústrias Horizonte L', 'relatorio', 2),
    ('Indústrias Horizonte L', 'dashboard', 1),
    ('Indústrias Horizonte L', 'integracao', 2),
    ('Holding Rubi M', 'relatorio', 4),
    ('Holding Rubi M', 'dashboard', 2),
    ('Holding Urano N', 'relatorio', 7),
    ('Holding Urano N', 'dashboard', 5),
    ('Indústrias Rubi O', 'relatorio', 4),
    ('Indústrias Rubi O', 'dashboard', 1),
    ('Indústrias Rubi O', 'integracao', 2),
    ('Log Everest P', 'relatorio', 3),
    ('Log Everest P', 'dashboard', 2),
    ('Log Everest P', 'integracao', 1),
    ('Med Nortis Q', 'relatorio', 2),
    ('Med Nortis Q', 'dashboard', 1),
    ('Med Nortis Q', 'integracao', 2),
    ('Indústrias Tramontana R', 'relatorio', 2),
    ('Indústrias Tramontana R', 'dashboard', 5),
    ('Indústrias Tramontana R', 'integracao', 1),
    ('Indústrias Tramontana S', 'relatorio', 4),
    ('Indústrias Tramontana S', 'dashboard', 1),
    ('Indústrias Tramontana S', 'integracao', 1),
    ('Grupo Câmbio T', 'relatorio', 4),
    ('Grupo Câmbio T', 'dashboard', 1),
    ('Grupo Câmbio T', 'integracao', 2),
    ('Cia Ourivés U', 'relatorio', 3),
    ('Cia Ourivés U', 'dashboard', 5),
    ('Cia Ourivés U', 'integracao', 1),
    ('Rede Ourivés V', 'relatorio', 5),
    ('Rede Ourivés V', 'dashboard', 3),
    ('Rede Ourivés V', 'integracao', 2),
    ('Cia Horizonte W', 'relatorio', 4),
    ('Cia Horizonte W', 'dashboard', 1),
    ('Cia Horizonte W', 'integracao', 1),
    ('Indústrias Estrela X', 'relatorio', 3),
    ('Indústrias Estrela X', 'dashboard', 5),
    ('Indústrias Estrela X', 'integracao', 2),
    ('Cia Estrela Y', 'relatorio', 4),
    ('Cia Estrela Y', 'dashboard', 5),
    ('Cia Estrela Y', 'integracao', 1),
    ('Indústrias Tramontana Z', 'relatorio', 7),
    ('Indústrias Tramontana Z', 'dashboard', 5),
    ('Indústrias Tramontana Z', 'integracao', 2),
    ('Agro Cristalina A', 'relatorio', 4),
    ('Agro Cristalina A', 'dashboard', 3),
    ('Agro Cristalina A', 'integracao', 1),
    ('Indústrias Cristalina B', 'relatorio', 2),
    ('Indústrias Cristalina B', 'dashboard', 2),
    ('Indústrias Cristalina B', 'integracao', 1),
    ('Med Urano C', 'relatorio', 6),
    ('Med Urano C', 'dashboard', 5),
    ('Med Urano C', 'integracao', 1),
    ('Holding Bandeirante D', 'relatorio', 7),
    ('Holding Bandeirante D', 'dashboard', 3),
    ('Indústrias Aurora E', 'relatorio', 3),
    ('Indústrias Aurora E', 'dashboard', 2),
    ('Indústrias Aurora E', 'integracao', 1),
    ('Indústrias Nortis F', 'relatorio', 5),
    ('Indústrias Nortis F', 'dashboard', 4),
    ('Agro Ipê G', 'relatorio', 6),
    ('Agro Ipê G', 'dashboard', 5),
    ('Agro Ipê G', 'integracao', 1),
    ('Cia Nortis H', 'relatorio', 5),
    ('Cia Nortis H', 'dashboard', 2),
    ('Cia Nortis H', 'integracao', 1)
) as v(projeto, tipo, quantidade)
join projetos p on p.nome = v.projeto
cross join generate_series(1, v.quantidade);

-- ─────────────────────── squads (§2.0, cada cadeira sai do time) ───────────────────────
insert into alocacoes (projeto_id, cargo_id, pessoa_id)
select p.id, c.id, pe.id
from (values
    ('Grupo Vértice A', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Grupo Vértice A', 'Analista Sênior', 'Otávio Lima'),
    ('Grupo Vértice A', 'Líder Técnico', 'Sofia Mendes'),
    ('Grupo Vértice A', 'Especialista', 'Leandro Bastos'),
    ('Agro Everest B', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Agro Everest B', 'Analista Sênior', 'Paula Monteiro'),
    ('Agro Everest B', 'Líder Técnico', 'Sofia Mendes'),
    ('Agro Everest B', 'Especialista', 'Isabela Prado'),
    ('Indústrias Ferrolar C', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Indústrias Ferrolar C', 'Analista Sênior', 'Paula Monteiro'),
    ('Indústrias Ferrolar C', 'Líder Técnico', 'Sofia Mendes'),
    ('Indústrias Ferrolar C', 'Especialista', 'Isabela Prado'),
    ('Indústrias Urano D', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Indústrias Urano D', 'Analista Sênior', 'Otávio Lima'),
    ('Indústrias Urano D', 'Líder Técnico', 'Sofia Mendes'),
    ('Indústrias Urano D', 'Especialista', 'Henrique Sales'),
    ('Indústrias Cristalina E', 'Analista', 'Bruno Tavares'),
    ('Indústrias Cristalina E', 'Especialista', 'Gabriela Rocha'),
    ('Indústrias Cristalina E', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Indústrias Cristalina E', 'Analista Sênior', 'Nelson Braga'),
    ('Indústrias Cristalina E', 'Arquiteto de Dados', 'Rafael Antunes'),
    ('Log Horizonte F', 'Analista', 'Bruno Tavares'),
    ('Log Horizonte F', 'Especialista', 'Karina Lopes'),
    ('Log Horizonte F', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Log Horizonte F', 'Analista Sênior', 'Nelson Braga'),
    ('Log Horizonte F', 'Arquiteto de Dados', 'Rafael Antunes'),
    ('Holding Serra Azul G', 'Analista', 'Bruno Tavares'),
    ('Holding Serra Azul G', 'Especialista', 'Gabriela Rocha'),
    ('Holding Serra Azul G', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Holding Serra Azul G', 'Analista Sênior', 'Nelson Braga'),
    ('Holding Serra Azul G', 'Arquiteto de Dados', 'Rafael Antunes'),
    ('Grupo Rubi H', 'Analista', 'Camila Duarte'),
    ('Grupo Rubi H', 'Especialista', 'Henrique Sales'),
    ('Grupo Rubi H', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Grupo Rubi H', 'Analista Sênior', 'Otávio Lima'),
    ('Grupo Rubi H', 'Arquiteto de Dados', 'Rafael Antunes'),
    ('Agro Bandeirante I', 'Analista', 'Ana Ribeiro'),
    ('Agro Bandeirante I', 'Especialista', 'João Vasques'),
    ('Agro Bandeirante I', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Agro Bandeirante I', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Agro Bandeirante I', 'Arquiteto de Dados', 'Rafael Antunes'),
    ('Grupo Marfim J', 'Analista', 'Diego Falcão'),
    ('Grupo Marfim J', 'Especialista', 'Isabela Prado'),
    ('Grupo Marfim J', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Grupo Marfim J', 'Analista Sênior', 'Paula Monteiro'),
    ('Grupo Marfim J', 'Arquiteto de Dados', 'Rafael Antunes'),
    ('Log Jacarandá K', 'Analista', 'Bruno Tavares'),
    ('Log Jacarandá K', 'Especialista', 'Gabriela Rocha'),
    ('Log Jacarandá K', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Log Jacarandá K', 'Analista Sênior', 'Nelson Braga'),
    ('Log Jacarandá K', 'Arquiteto de Dados', 'Rafael Antunes'),
    ('Grupo Diamantina L', 'Analista', 'Eduarda Nunes'),
    ('Grupo Diamantina L', 'Especialista', 'Felipe Marques'),
    ('Grupo Diamantina L', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Grupo Diamantina L', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Grupo Diamantina L', 'Arquiteto de Dados', 'Rafael Antunes'),
    ('Holding Estrela M', 'Analista', 'Eduarda Nunes'),
    ('Holding Estrela M', 'Especialista', 'João Vasques'),
    ('Holding Estrela M', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Holding Estrela M', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Holding Estrela M', 'Arquiteto de Dados', 'Rafael Antunes'),
    ('Indústrias Ourivés N', 'Analista', 'Ana Ribeiro'),
    ('Indústrias Ourivés N', 'Especialista', 'Felipe Marques'),
    ('Indústrias Ourivés N', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Indústrias Ourivés N', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Indústrias Ourivés N', 'Arquiteto de Dados', 'Rafael Antunes'),
    ('Agro Estrela O', 'Analista', 'Eduarda Nunes'),
    ('Agro Estrela O', 'Especialista', 'Felipe Marques'),
    ('Agro Estrela O', 'Líder Técnico', 'Sofia Mendes'),
    ('Agro Estrela O', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Log Zênite P', 'Analista', 'Camila Duarte'),
    ('Log Zênite P', 'Especialista', 'Leandro Bastos'),
    ('Log Zênite P', 'Líder Técnico', 'Sofia Mendes'),
    ('Log Zênite P', 'Analista Sênior', 'Otávio Lima'),
    ('Rede Lumina Q', 'Analista', 'Diego Falcão'),
    ('Rede Lumina Q', 'Especialista', 'Isabela Prado'),
    ('Rede Lumina Q', 'Líder Técnico', 'Sofia Mendes'),
    ('Rede Lumina Q', 'Analista Sênior', 'Paula Monteiro'),
    ('Med Vértice R', 'Analista', 'Ana Ribeiro'),
    ('Med Vértice R', 'Especialista', 'Felipe Marques'),
    ('Med Vértice R', 'Líder Técnico', 'Sofia Mendes'),
    ('Med Vértice R', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Log Solaris S', 'Analista', 'Diego Falcão'),
    ('Log Solaris S', 'Especialista', 'Isabela Prado'),
    ('Log Solaris S', 'Líder Técnico', 'Sofia Mendes'),
    ('Log Solaris S', 'Analista Sênior', 'Paula Monteiro'),
    ('Log Montana T', 'Analista', 'Bruno Tavares'),
    ('Log Montana T', 'Especialista', 'Karina Lopes'),
    ('Log Montana T', 'Líder Técnico', 'Sofia Mendes'),
    ('Log Montana T', 'Analista Sênior', 'Nelson Braga'),
    ('Med Everest U', 'Analista', 'Camila Duarte'),
    ('Med Everest U', 'Especialista', 'Henrique Sales'),
    ('Med Everest U', 'Líder Técnico', 'Sofia Mendes'),
    ('Med Everest U', 'Analista Sênior', 'Otávio Lima'),
    ('Rede Guaraí V', 'Analista', 'Bruno Tavares'),
    ('Rede Guaraí V', 'Especialista', 'Gabriela Rocha'),
    ('Rede Guaraí V', 'Líder Técnico', 'Sofia Mendes'),
    ('Rede Guaraí V', 'Analista Sênior', 'Nelson Braga'),
    ('Rede Jacarandá W', 'Analista', 'Eduarda Nunes'),
    ('Rede Jacarandá W', 'Especialista', 'João Vasques'),
    ('Rede Jacarandá W', 'Líder Técnico', 'Sofia Mendes'),
    ('Rede Jacarandá W', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Rede Pampulha X', 'Analista', 'Diego Falcão'),
    ('Rede Pampulha X', 'Especialista', 'Isabela Prado'),
    ('Rede Pampulha X', 'Líder Técnico', 'Sofia Mendes'),
    ('Rede Pampulha X', 'Analista Sênior', 'Paula Monteiro'),
    ('Holding Everest Y', 'Analista', 'Eduarda Nunes'),
    ('Holding Everest Y', 'Especialista', 'Felipe Marques'),
    ('Holding Everest Y', 'Líder Técnico', 'Sofia Mendes'),
    ('Holding Everest Y', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Cia Estrela Z', 'Analista', 'Bruno Tavares'),
    ('Cia Estrela Z', 'Especialista', 'Karina Lopes'),
    ('Cia Estrela Z', 'Líder Técnico', 'Sofia Mendes'),
    ('Cia Estrela Z', 'Analista Sênior', 'Nelson Braga'),
    ('Agro Pampulha A', 'Analista', 'Ana Ribeiro'),
    ('Agro Pampulha A', 'Especialista', 'João Vasques'),
    ('Agro Pampulha A', 'Líder Técnico', 'Sofia Mendes'),
    ('Agro Pampulha A', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Rede Nortis B', 'Analista', 'Eduarda Nunes'),
    ('Rede Nortis B', 'Especialista', 'Felipe Marques'),
    ('Rede Nortis B', 'Líder Técnico', 'Sofia Mendes'),
    ('Rede Nortis B', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Indústrias Itaúna C', 'Analista', 'Bruno Tavares'),
    ('Indústrias Itaúna C', 'Especialista', 'Karina Lopes'),
    ('Indústrias Itaúna C', 'Líder Técnico', 'Sofia Mendes'),
    ('Indústrias Itaúna C', 'Analista Sênior', 'Nelson Braga'),
    ('Agro Verdaz D', 'Analista', 'Bruno Tavares'),
    ('Agro Verdaz D', 'Especialista', 'Gabriela Rocha'),
    ('Agro Verdaz D', 'Líder Técnico', 'Sofia Mendes'),
    ('Agro Verdaz D', 'Analista Sênior', 'Nelson Braga'),
    ('Log Ipê E', 'Analista', 'Camila Duarte'),
    ('Log Ipê E', 'Especialista', 'Leandro Bastos'),
    ('Log Ipê E', 'Líder Técnico', 'Sofia Mendes'),
    ('Log Ipê E', 'Analista Sênior', 'Otávio Lima'),
    ('Agro Vértice F', 'Analista', 'Eduarda Nunes'),
    ('Agro Vértice F', 'Especialista', 'João Vasques'),
    ('Agro Vértice F', 'Líder Técnico', 'Sofia Mendes'),
    ('Agro Vértice F', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Agro Everest G', 'Analista', 'Ana Ribeiro'),
    ('Agro Everest G', 'Especialista', 'Felipe Marques'),
    ('Agro Everest G', 'Líder Técnico', 'Sofia Mendes'),
    ('Agro Everest G', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Log Ferrolar H', 'Analista', 'Bruno Tavares'),
    ('Log Ferrolar H', 'Especialista', 'Gabriela Rocha'),
    ('Log Ferrolar H', 'Líder Técnico', 'Sofia Mendes'),
    ('Log Ferrolar H', 'Analista Sênior', 'Nelson Braga'),
    ('Holding Xisto I', 'Analista', 'Bruno Tavares'),
    ('Holding Xisto I', 'Especialista', 'Karina Lopes'),
    ('Holding Xisto I', 'Líder Técnico', 'Sofia Mendes'),
    ('Holding Xisto I', 'Analista Sênior', 'Nelson Braga'),
    ('Holding Marfim J', 'Analista', 'Bruno Tavares'),
    ('Holding Marfim J', 'Especialista', 'Karina Lopes'),
    ('Holding Marfim J', 'Líder Técnico', 'Sofia Mendes'),
    ('Holding Marfim J', 'Analista Sênior', 'Nelson Braga'),
    ('Cia Delta Sul K', 'Analista', 'Eduarda Nunes'),
    ('Cia Delta Sul K', 'Especialista', 'Felipe Marques'),
    ('Cia Delta Sul K', 'Líder Técnico', 'Sofia Mendes'),
    ('Cia Delta Sul K', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Rede Ourivés L', 'Analista', 'Diego Falcão'),
    ('Rede Ourivés L', 'Especialista', 'Isabela Prado'),
    ('Rede Ourivés L', 'Líder Técnico', 'Sofia Mendes'),
    ('Rede Ourivés L', 'Analista Sênior', 'Paula Monteiro'),
    ('Log Montana M', 'Especialista', 'Gabriela Rocha'),
    ('Log Montana M', 'Analista Sênior', 'Nelson Braga'),
    ('Log Montana M', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Log Montana M', 'Líder Técnico', 'Sofia Mendes'),
    ('Holding Horizonte N', 'Especialista', 'Gabriela Rocha'),
    ('Holding Horizonte N', 'Analista Sênior', 'Nelson Braga'),
    ('Holding Horizonte N', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Holding Horizonte N', 'Líder Técnico', 'Sofia Mendes'),
    ('Agro Solaris O', 'Especialista', 'Leandro Bastos'),
    ('Agro Solaris O', 'Analista Sênior', 'Otávio Lima'),
    ('Agro Solaris O', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Agro Solaris O', 'Líder Técnico', 'Sofia Mendes'),
    ('Indústrias Rubi P', 'Especialista', 'Henrique Sales'),
    ('Indústrias Rubi P', 'Analista Sênior', 'Otávio Lima'),
    ('Indústrias Rubi P', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Indústrias Rubi P', 'Líder Técnico', 'Sofia Mendes'),
    ('Rede Xisto Q', 'Especialista', 'Isabela Prado'),
    ('Rede Xisto Q', 'Analista Sênior', 'Paula Monteiro'),
    ('Rede Xisto Q', 'Gerente de Projeto', 'Vanessa Klein'),
    ('Rede Xisto Q', 'Líder Técnico', 'Sofia Mendes'),
    ('Rede Diamantina R', 'Especialista', 'Isabela Prado'),
    ('Rede Diamantina R', 'Analista Sênior', 'Paula Monteiro'),
    ('Rede Diamantina R', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Rede Diamantina R', 'Líder Técnico', 'Sofia Mendes'),
    ('Log Kaporã S', 'Especialista', 'João Vasques'),
    ('Log Kaporã S', 'Analista Sênior', 'Mariana Cordeiro'),
    ('Log Kaporã S', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Log Kaporã S', 'Líder Técnico', 'Sofia Mendes'),
    ('Med Andorra T', 'Especialista', 'Karina Lopes'),
    ('Med Andorra T', 'Analista Sênior', 'Nelson Braga'),
    ('Med Andorra T', 'Gerente de Projeto', 'Thiago Rezende'),
    ('Med Andorra T', 'Líder Técnico', 'Sofia Mendes'),
    ('Grupo Lumina U', 'Analista', 'Diego Falcão'),
    ('Grupo Lumina U', 'Especialista', 'Isabela Prado'),
    ('Agro Ferrolar V', 'Analista', 'Camila Duarte'),
    ('Agro Ferrolar V', 'Especialista', 'Henrique Sales'),
    ('Log Tramontana W', 'Analista', 'Bruno Tavares'),
    ('Log Tramontana W', 'Especialista', 'Karina Lopes'),
    ('Indústrias Rubi X', 'Analista', 'Camila Duarte'),
    ('Indústrias Rubi X', 'Especialista', 'Henrique Sales'),
    ('Holding Estrela Y', 'Analista', 'Bruno Tavares'),
    ('Holding Estrela Y', 'Especialista', 'Karina Lopes'),
    ('Holding Andorra Z', 'Analista', 'Diego Falcão'),
    ('Holding Andorra Z', 'Especialista', 'Isabela Prado'),
    ('Med Ipê A', 'Analista', 'Bruno Tavares'),
    ('Med Marfim B', 'Analista', 'Bruno Tavares'),
    ('Log Nortis C', 'Analista', 'Camila Duarte'),
    ('Log Andorra D', 'Analista', 'Bruno Tavares'),
    ('Agro Zênite E', 'Analista', 'Eduarda Nunes'),
    ('Rede Horizonte F', 'Analista', 'Camila Duarte'),
    ('Rede Urano G', 'Analista', 'Bruno Tavares'),
    ('Log Verdaz H', 'Analista', 'Diego Falcão'),
    ('Log Vértice I', 'Analista', 'Camila Duarte'),
    ('Holding Aurora J', 'Analista', 'Bruno Tavares'),
    ('Agro Tramontana K', 'Analista', 'Diego Falcão'),
    ('Med Cristalina L', 'Analista', 'Bruno Tavares'),
    ('Rede Diamantina M', 'Analista', 'Camila Duarte'),
    ('Log Montana N', 'Analista', 'Ana Ribeiro'),
    ('Rede Diamantina O', 'Analista', 'Bruno Tavares'),
    ('Rede Rubi P', 'Analista', 'Camila Duarte'),
    ('Log Guaraí Q', 'Analista', 'Diego Falcão'),
    ('Indústrias Ipê R', 'Analista', 'Diego Falcão'),
    ('Agro Vértice S', 'Analista', 'Diego Falcão'),
    ('Grupo Lumina T', 'Analista', 'Camila Duarte'),
    ('Grupo Guaraí U', 'Analista', 'Camila Duarte'),
    ('Rede Solaris V', 'Analista', 'Camila Duarte'),
    ('Rede Vértice W', 'Analista', 'Diego Falcão'),
    ('Rede Marfim X', 'Analista', 'Camila Duarte'),
    ('Holding Lumina Y', 'Analista', 'Camila Duarte'),
    ('Log Diamantina Z', 'Analista', 'Diego Falcão'),
    ('Grupo Guaraí A', 'Analista', 'Diego Falcão'),
    ('Med Xisto B', 'Analista', 'Diego Falcão'),
    ('Holding Serra Azul C', 'Analista', 'Camila Duarte'),
    ('Rede Delta Sul D', 'Analista', 'Diego Falcão'),
    ('Indústrias Diamantina E', 'Analista', 'Diego Falcão'),
    ('Cia Marfim F', 'Analista', 'Ana Ribeiro'),
    ('Med Kaporã G', 'Analista', 'Diego Falcão'),
    ('Log Lumina H', 'Analista', 'Diego Falcão'),
    ('Cia Serra Azul I', 'Analista', 'Eduarda Nunes'),
    ('Log Bandeirante J', 'Analista', 'Camila Duarte'),
    ('Grupo Xisto K', 'Analista', 'Camila Duarte'),
    ('Indústrias Horizonte L', 'Analista', 'Camila Duarte'),
    ('Holding Rubi M', 'Analista', 'Bruno Tavares'),
    ('Holding Urano N', 'Analista', 'Eduarda Nunes'),
    ('Indústrias Rubi O', 'Analista', 'Ana Ribeiro'),
    ('Log Everest P', 'Analista', 'Eduarda Nunes'),
    ('Med Nortis Q', 'Analista', 'Ana Ribeiro'),
    ('Indústrias Tramontana R', 'Analista', 'Ana Ribeiro'),
    ('Indústrias Tramontana S', 'Analista', 'Camila Duarte'),
    ('Grupo Câmbio T', 'Analista', 'Camila Duarte'),
    ('Cia Ourivés U', 'Analista', 'Eduarda Nunes'),
    ('Rede Ourivés V', 'Analista', 'Ana Ribeiro'),
    ('Cia Horizonte W', 'Analista', 'Bruno Tavares'),
    ('Indústrias Estrela X', 'Analista', 'Eduarda Nunes'),
    ('Cia Estrela Y', 'Analista', 'Bruno Tavares'),
    ('Indústrias Tramontana Z', 'Analista', 'Ana Ribeiro'),
    ('Agro Cristalina A', 'Analista', 'Camila Duarte'),
    ('Indústrias Cristalina B', 'Analista', 'Ana Ribeiro'),
    ('Med Urano C', 'Analista', 'Diego Falcão'),
    ('Holding Bandeirante D', 'Analista', 'Bruno Tavares'),
    ('Indústrias Aurora E', 'Analista', 'Diego Falcão'),
    ('Indústrias Nortis F', 'Analista', 'Diego Falcão'),
    ('Agro Ipê G', 'Analista', 'Camila Duarte'),
    ('Cia Nortis H', 'Analista', 'Diego Falcão')
) as v(projeto, cargo, pessoa)
join projetos p on p.nome = v.projeto
join cargos c on c.nome = v.cargo
join pessoas pe on pe.nome = v.pessoa;
